Fractal: CoordPlane.o Complex.o main.cpp
g++ CoordPlane.o Complex.o main.cpp ‘Magick++-config --cppflags --cxxflags --ldflags --libs‘
CoordPlane.o: CoordPlane.cpp CoordPlane.h
g++ -c CoordPlane.cpp
Complex.o: Complex.cpp Complex.h
g++ -c Complex.cpp
clean:
rm -f *.o a.out